--- 
blobstore: 
  provider: s3
  options: 
    bucket_name: boshreleases
    iam_name: boshblobs-download
    s3_owner: drnicwilliams@gmail.com
    access_key_id: AKIAIDC76IQWCWDL3QKQ
    secret_access_key: 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
    encryption_key: asdfasfdasdfasdf
